name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        python-version: ["3.12", "3.13", "3.14"]
        extra: ["tpot", "all"]
    steps:
      - name: Check out repo
        uses: actions/checkout@v7.0.1

      - name: Install uv
        uses: astral-sh/setup-uv@v8.3.2
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv sync --extra ${{ matrix.extra }} --dev --frozen

      - name: Run tests
        run: uv run pytest
