on: [push, pull_request]

jobs:
  python-compat:
    strategy:
      matrix:
        python-version: ["3.12", "3.14"]
        resolution: ["--resolution lowest-direct", "--upgrade"]
    uses: ./.github/workflows/_run_tests.yml
    with:
      python-version: ${{ matrix.python-version }}
      uv-opts: "${{ matrix.resolution }} --extra all"

  extras-isolation:
    strategy:
      matrix:
        extra: ["tpot", "all"]
    uses: ./.github/workflows/_run_tests.yml
    with:
      python-version: "3.14"
      uv-opts: "--upgrade --extra ${{ matrix.extra }}"
